name: weather_app
description: Aplikasi cuaca sederhana menggunakan Flutter
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  intl: ^0.19.0
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.5.3
  geolocator: ^10.1.0
  # fl_chart removed due to Windows build incompatibility with current Flutter SDK

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
